name: iOS CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: actions/setup-xcode@v2
      with:
        xcode-version: '13.2' # Use the version compatible with iPhone 14 Pro

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build and Test
      run: |
        xcodebuild clean build -workspace YourApp.xcworkspace -scheme YourApp -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 14 Pro'

    - name: Archive Build
      run: xcodebuild archive -workspace YourApp.xcworkspace -scheme YourApp -destination 'generic/platform=iOS' -archivePath build/YourApp.xcarchive

    - name: Create IPA
      run: xcodebuild -exportArchive -archivePath build/YourApp.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath build

    - name: Deploy to App Store (example, replace with your deployment step)
      run: fastlane release
