name: Swift

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
     - name: Build
        run: xcodebuild clean build test -workspace ios-expert.xcworkspace -scheme "ios-expert" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.2,name=iPhone 11 Pro" -derivedDataPath Build/ -enableCodeCoverage YES ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
  
